### ISSUE TITLE
Move blog.nav.uninett.no into nav-landing-page

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/nav-landing-page#4]
### Background

https://blog.nav.uninett.no/ is a blogger.com-based (Google) blog published by the NAV developer team. Although it was meant to publish any kind of NAV-related article (like tips&tricks, suggestions and guides, release announcements), it has mainly been used for release announcements in the last few years. Comments are rarely received on the blog (I can remember maybe one instance of this since the blog was started).

Publishing at blogger.com is a bit of a hassle, especially since most release announcements are written in markdown, which is not supported by blogger.com (that I know) - so they need to be converted and uploaded as raw HTML to blogger.com.

We also need to keep track of a team Google account + password to use the blog.

### The idea

*nav-landing-page* is now a statically generated Hugo site. Implementing a blog section on this site is relatively straightforward in Hugo terms (about a gajillion examples even exist online). Publishing a new release announcement would be as simple as committing a new markdown-formatted file to the Git repository and pushing it to GitHub, and our automation will take care of updating the live site at https://nav.uninett.no

### Tasks

- [x] Create a blog section of the Hugo site (under `/blog/`), with a corresponding blog post content type.
  - The design should follow from the existing design template
- [x] Convert existing blog posts from https://blog.nav.uninett.no/ into individual markdown documents, with the proper metadata (this might require a bit of research to find the most convenient way)
- [x] Create an RSS feed version of the blog (also statically generated by Hugo)
  - All NAV installations today come with a feed reader widget on the default dashboard, which shows the RSS feed contents of the current blog site.
  - Once migrated, we need to serve https://blog.nav.uninett.no/ ourselves to make sure all requests are redirected to the new site. Some planning may be required so that we can automatically map redirects from the existing `blog.nav.uninett.no` URL scheme to a new one under `nav.uninett.no/blog/`
- [x] Convert all the blog posts that have been made after the initial migration
- [x] Set up a new blog.nav.uninett.no site in our own infrastructure to act as a redirector of requests to the new blog location
  - Individual blog posts should be redirected to their new locations
  - RSS/Atom feeds should be redirected to their new locations
  - New site doesn't feature taxonomy pages (yet), but when they do, label pages/searches should probably redirect to the corresponding new locations.
